apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "test-chart.fullname" . }}-ordpress-mysql
  labels:
    app: wordpress
  {{- include "test-chart.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: mysql
    {{- include "test-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
      {{- include "test-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mysql-pass
        - name: MYSQL_DATABASE
          value: {{ quote .Values.ordpressMysql.mysql.env.mysqlDatabase }}
        - name: MYSQL_USER
          value: {{ quote .Values.ordpressMysql.mysql.env.mysqlUser }}
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mysql-pass
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.ordpressMysql.mysql.image.repository }}:{{ .Values.ordpressMysql.mysql.image.tag
          | default .Chart.AppVersion }}
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-persistent-storage
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: {{ include "test-chart.fullname" . }}-mysql-pv-claim
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "test-chart.fullname" . }}-ordpress
  labels:
    app: wordpress
  {{- include "test-chart.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
    {{- include "test-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
      {{- include "test-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: WORDPRESS_DB_HOST
          value: {{ quote .Values.ordpress.wordpress.env.wordpressDbHost }}
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mysql-pass
        - name: WORDPRESS_DB_USER
          value: {{ quote .Values.ordpress.wordpress.env.wordpressDbUser }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.ordpress.wordpress.image.repository }}:{{ .Values.ordpress.wordpress.image.tag
          | default .Chart.AppVersion }}
        name: wordpress
        ports:
        - containerPort: 80
          name: wordpress
        resources: {}
        volumeMounts:
        - mountPath: /var/www/html
          name: wordpress-persistent-storage
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: {{ include "test-chart.fullname" . }}-p-pv-claim