apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "test-chart.fullname" . }}-mysql-pv-claim
  labels:
    app: wordpress
  {{- include "test-chart.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.mysqlPvClaim.storageRequest | quote }}