apiVersion: v1
kind: Service
metadata:
  name: {{ include "test-chart.fullname" . }}-ordpress-mysql
  labels:
    app: wordpress
  {{- include "test-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ordpressMysql.type }}
  selector:
    app: wordpress
    tier: mysql
  {{- include "test-chart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.ordpressMysql.ports | toYaml | nindent 2 -}}